// string file
const Strings = {
  appName: 'Demo App',
  loading: 'Loading',
  pleaseWait: 'Please Wait...',
  logout: 'Logout',
  logoutMsg: 'Are you sure you want to logout?',
  deleteProduct: 'Are you sure you want to delete?',
  addProductMsg: 'Are you sure you want to add this product?',
  updateProductMsg: 'Are you sure you want to update this product?',
  yes: 'Yes',
  no: 'No',
  welcome: 'Welcome',
  ok: 'Ok',
  cancel: 'Cancel',
  proErr: 'Delete product',
  proDeleteMsg: 'Product deleted successfully!',
  proAddMsg: 'Product added successfully!',
  proUpdateMsg: 'Product updated successfully!',
  errorMsg: 'Something went to wrong',
  fieldsError: 'Please fill all fields',
  blocksAction: 'Database policy blocks this action',
  unknownError: 'Unknown error',
  failed: 'failed',
  add: 'Add',
  update: 'Update',
  enable: 'Enable',
  INSERT: 'INSERT',
  UPDATE: 'UPDATE',
  policiesErr: 'policies for table products in Supabase',
  price: 'Price',
  productName: 'Product Name',
  quantity: 'Quantity',
  addProduct: 'Add Product',
  updateProduct: 'Update Product',
  noData: 'No data found. please add the product.',
};

export default Strings;
